name: test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  ACTIONS_RUNNER_DEBUG: true

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge geiger
        run: |
          forge geiger --check
        id: geiger

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --names
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
